name: YouTube_24-7_Stream
on:
  schedule:
    - cron: '0 */6 * * *' 
  workflow_dispatch: 

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and Stream
        run: |
          # आपकी वेबसाइट से डेटा उठाना
          INFO=$(curl -s "https://dsrblackpanel.xo.je/get_data.php")
          V_URL=$(echo $INFO | cut -d'|' -f1)
          S_KEY=$(echo $INFO | cut -d'|' -f2)
          
          # यूट्यूब पर ब्रॉडकास्ट भेजना
          ffmpeg -re -stream_loop -1 -i "$V_URL" \
          -c:v libx264 -preset veryfast -b:v 3000k -maxrate 3000k -bufsize 6000k \
          -pix_fmt yuv420p -g 50 -c:a aac -b:a 128k -ar 44100 \
          -f flv "rtmp://a.rtmp.youtube.com/live2/$S_KEY"
          
